### ISSUE TITLE
Why not allow non-square icons?

### ISSUE THREAD

**Issue by dhpollack** [PolymerElements/iron-iconset-svg#3]
It seems fairly trivial to add non-square icons.  All one would have to do is change line change the cloneIcon function to allow for an x-size and a y-size and then change the set viewBox function to reflect this change.  But perhaps there is a reason you only allow square icons.

Is there a reason we couldn't have an size for length and width so we could add non-square icon sets?

**Comment by dhpollack** [comment]
@cdata any opinion on this? I wouldn't mind creating a pull request to add this functionality.

**Comment by jennvoss** [comment]
I submitted a pull request to allow this: https://github.com/PolymerElements/iron-iconset-svg/pull/13

If you set a viewBox attribute on your svg's, this change will respect that value instead of resetting it to the iconset size. I've been using this in my own project without any issues, but if you see a downside to this please let me know.

**Comment by dhpollack** [comment]
@jennvoss cool!

**Comment by notwaldorf** [comment]
This looks like it's been fixed
