### ISSUE TITLE
SVG elements are always focusable in IE11

### ISSUE THREAD

**Issue by braddiver** [PolymerElements/iron-iconset-svg#46]
### Description

Any SVG elements written by `iron-iconset-svg` will be put into the tab order of the page in IE11.
### Expected outcome

SVG elements should not be focusable by default

Adding this line of code in the `_prepareSvgClone` function fixes the problem:
`svg.setAttribute('focusable', false);`

**Comment by dlockhart** [comment]
Adding some extra details from [a duplicate issue I created](https://github.com/PolymerElements/iron-icon/issues/71) in iron-icon:

This occurs In both Edge and IE11, and occurs even with a `tabindex="-1"` -- since apparently that's part of the [SVG2 spec](https://www.w3.org/TR/SVG2/struct.html#tabindexattribute), which IE does not yet support.

### Live Demo

https://jsbin.com/subavuciji/edit?html,output

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

### Potential Fix

As noted above in the description, and from [this article on StackOverflow](http://stackoverflow.com/questions/18646111/disable-onfocus-event-for-svg-element), set the `focusable` attribute to `false`: `<svg focusable="false"></svg>`

**Comment by timove** [comment]
Tested on IE 11: adding `svg.setAttribute('focusable', 'false');` into `_prepareSvgClone` works as expected.

**Comment by AlvaroGonzalezCans** [comment]
Hello, what is the state of this issue?
